version: 2.1

orbs:
  ruby: circleci/ruby@1.1.3

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.6-node
        environment:
          RAILS_ENV: test
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Setup database
          command: bundle exec rake db:create && bundle exec rake db:migrate
      - run:
          name: Run tests
          command: bundle exec rake spec
