#############################################################################
# will_filter configuration
#
# Default settings for all environments
# 
# You can overload any feature for any environment by changing the 
# environment settings at the bottom of the file. 
#
# Alternatively, you can overload any of the methods of Tr8n::Config
#############################################################################

defaults: &defaults
  containers:
    nil:                Wf::NilContainer
    numeric:            Wf::NumericContainer
    numeric_range:      Wf::NumericRangeContainer
    numeric_delimited:  Wf::NumericDelimitedContainer
    date_time_range:    Wf::DateTimeRangeContainer
    single_date:        Wf::SingleDateContainer
    date:               Wf::DateContainer
    date_time:          Wf::DateTimeContainer
    date_range:         Wf::DateRangeContainer
    text:               Wf::TextContainer
    text_delimited:     Wf::TextDelimitedContainer
    boolean:            Wf::BooleanContainer
    
  mapping:
    bigint:             [nil, numeric, numeric_range, numeric_delimited]
    numeric:            [nil, numeric, numeric_range, numeric_delimited]
    smallint:           [nil, numeric, numeric_range, numeric_delimited]
    integer:            [nil, numeric, numeric_range, numeric_delimited]
    int:                [nil, numeric, numeric_range, numeric_delimited]
    double:             [nil, numeric, numeric_range, numeric_delimited]
    timestamp:          [nil, date_time, date_time_range, single_date]
    datetime:           [nil, date_time, date_time_range, single_date]
    date:               [nil, date, date_range]
    character:          [nil, text, text_delimited]
    varchar:            [nil, text, text_delimited]
    text:               [nil, text, text_delimited]
    text[]:             [nil, text, text_delimited]
    bytea:              [nil, text, text_delimited]
    boolean:            [nil, boolean]
    tinyint:            [nil, boolean]

  operator_order:       [is, is_not, is_on, is_in, is_provided, is_not_provided, is_after, is_before, is_in_the_range, contains, does_not_contain, starts_with, ends_with, is_greater_than, is_less_than, is_filtered_by] 
  export_formats:       [table, csv, xml, json]
  
#############################################################################
# Environment Settings
# You can overload any feature defined in the defaults for any environment
#############################################################################
development:
  <<: *defaults
  
test:
  <<: *defaults
      
qa:
  <<: *defaults

stage:
  <<: *defaults

production:
  <<: *defaults
